### ISSUE TITLE
Error : Attended

### ISSUE THREAD

**Issue by Killemall812** [KingdomFirst/rock-attended-checkin#31]
Ive been trying to get this to work for months. Im really unsure what I have done wrong. Im sure you guys will look at the code below and see it straight away .. Please please someone help ? I get this as soon as I search for a family name or any name for that matter. Everything works fine in /Checkin but if I use /attendedcheckin I get this error..  

Thanks guys .

![screen shot 2017-08-31 at 8 46 05 pm](https://user-images.githubusercontent.com/31510415/29924647-302f8752-8e90-11e7-8ddf-ed48fc729fb0.png)

NullReferenceException in Rock

Message
Object reference not set to an instance of an object.
Stack Trace
   at Rock.Workflow.Action.CheckIn.FilterGroupsBySpecialNeeds.Execute(RockContext rockContext, WorkflowAction action, Object entity, List`1& errorMessages)
   at Rock.Model.WorkflowAction.Process(RockContext rockContext, Object entity, List`1& errorMessages)
   at Rock.Model.WorkflowActivity.Process(RockContext rockContext, Object entity, List`1& errorMessages)
   at Rock.Model.Workflow.ProcessActivity(RockContext rockContext, DateTime processStartTime, Object entity, List`1& errorMessages)
   at Rock.Model.Workflow.ProcessActivities(RockContext rockContext, Object entity, List`1& errorMessages)
   at Rock.Model.WorkflowService.Process(Workflow workflow, Object entity, List`1& errorMessages)
   at Rock.CheckIn.CheckInBlock.ProcessActivity(String activityName, List`1& errorMessages)
   at RockWeb.Plugins.cc_newspring.AttendedCheckin.FamilySelect.ProcessPeople(CheckInFamily selectedFamily) in c:\Inetpub\vhosts\calvarychapelalbany.com.au\my.calvarychapelalbany.com.au\Plugins\cc_newspring\AttendedCheckin\FamilySelect.ascx.cs:line 847
   at RockWeb.Plugins.cc_newspring.AttendedCheckin.FamilySelect.OnLoad(EventArgs e) in c:\Inetpub\vhosts\calvarychapelalbany.com.au\my.calvarychapelalbany.com.au\Plugins\cc_newspring\AttendedCheckin\FamilySelect.ascx.cs:line 149
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

**Comment by dcs619** [comment]
@Killemall812 Did you get an answer on this?  The error is occurring in the workflow action FilterBySpecialNeeds.  If you don't have Special Needs rooms at your church, you can delete the action from the workflow.

**Comment by dcs619** [comment]
Closing, resolution noted above
