### ISSUE TITLE
frequent null reference exceptions

### ISSUE THREAD

**Issue by CBC17044** [KingdomFirst/rock-attended-checkin#34]
The following exception has been occurring frequently for us when using our the Newspring attended checkin.

An exception has occurred. Details of this error can be found below:
An error occurred on the Rock Attended Check-in site on page: https://____________________/attendedcheckin/confirm
NullReferenceException in App_Web_2gwcbi2q
Message Object reference not set to an instance of an object.
Stack Trace
at RockWeb.Plugins.cc_newspring.AttendedCheckin.Confirm.gPersonList_Delete(Object sender, RowEventArgs e) in g:\pleskvhosts\ ________________\httpdocs\Plugins\cc_newspring\AttendedCheckin\Confirm.ascx.cs:line 340
at Rock.Web.UI.Controls.DeleteField.OnClick(RowEventArgs e)
at Rock.Web.UI.Controls.DeleteField.deleteFieldTemplate_LinkButtonClick(Object sender, RowEventArgs e)
at Rock.Web.UI.Controls.DeleteFieldTemplate.lbDelete_Click(Object sender, EventArgs e)
at System.Web.UI.WebControls.LinkButton.OnClick(EventArgs e)
at System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument)
at System.Web.UI.WebControls.LinkButton.System.Web.UI.IPostBackEventHandler.RaisePostBackEvent(String eventArgument)
at System.Web.UI.Page.RaisePostBackEvent(IPostBackEventHandler sourceControl, String eventArgument)
at System.Web.UI.Page.RaisePostBackEvent(NameValueCollection postData)
at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

**Comment by dcs619** [comment]
Not able to reproduce, but can add null checking on all fields in the Delete method.  Leaving open until null propagation operator is available in Rock v8.
