### ISSUE TITLE
Checkin Broken in V7

### ISSUE THREAD

**Issue by garrettjohnson** [KingdomFirst/rock-attended-checkin#36]
In V7 the Family Select page returns a System.NullReferenceException, Object reference not set to an instance of an object.

```
   at cc.newspring.AttendedCheckIn.Workflow.Action.CheckIn.SelectByBestFit.Execute(RockContext rockContext, WorkflowAction action, Object entity, List`1& errorMessages)
   at Rock.Model.WorkflowAction.Process(RockContext rockContext, Object entity, List`1& errorMessages)
   at Rock.Model.WorkflowActivity.Process(RockContext rockContext, Object entity, List`1& errorMessages)
   at Rock.Model.Workflow.ProcessActivity(RockContext rockContext, DateTime processStartTime, Object entity, List`1& errorMessages)
   at Rock.Model.Workflow.ProcessActivities(RockContext rockContext, Object entity, List`1& errorMessages)
   at Rock.Model.WorkflowService.Process(Workflow workflow, Object entity, List`1& errorMessages)
   at Rock.CheckIn.CheckInBlock.ProcessActivity(String activityName, List`1& errorMessages)
   at RockWeb.Plugins.cc_newspring.AttendedCheckin.FamilySelect.lbNext_Click(Object sender, EventArgs e) in \Plugins\cc_newspring\AttendedCheckin\FamilySelect.ascx.cs:line 208
   at System.Web.UI.WebControls.LinkButton.OnClick(EventArgs e)
   at System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
```

**Comment by garrettjohnson** [comment]
Looks like V7 requires the `Group Special Needs Attribute` to be selected. Might be worth updating the documentation to make note of this since it's not populated in the Attended Checkin workflow by default.

**Comment by dcs619** [comment]
@garrettjohnson I have an update for the plugin that needs to be pushed up and built for the Rock store.  That's one of the fixes included.

**Comment by K-Fritsch** [comment]
Ran into same issue when testing V7 Attended Check-in.  Tracked @garrettjohnson's question on Slack, then found the "how-to" steps for resolving from @dcs619's answer in the "Ask" section of Rock @  https://www.rockrms.com/Rock/Ask/Using/Questions/1862 . Posting this here in case anyone else runs into same issue b4 plugin or documentation is updated. Thank you!!

**Comment by dcs619** [comment]
Closing, this will be fixed in the next Rock Shop update and steps noted above.
