### ISSUE TITLE
When Confirming checkin

### ISSUE THREAD

**Issue by kennethporte** [KingdomFirst/rock-attended-checkin#39]
Hi All,

I get this issue when confirming attendance. Been trying to work with my team on this, but can't find a solution. Would really appreciate your help.

Thanks all!

---------------------------------------------------------------------------------------------
NullReferenceException in cc.newspring.AttendedCheckIn
Message
Object reference not set to an instance of an object.

Stack Trace

   at cc.newspring.AttendedCheckIn.Workflow.Action.CheckIn.SelectByMultipleAttended.Execute(RockContext rockContext, WorkflowAction action, Object entity, List`1& errorMessages)
   at Rock.Model.WorkflowAction.Process(RockContext rockContext, Object entity, List`1& errorMessages)
   at Rock.Model.WorkflowActivity.Process(RockContext rockContext, Object entity, List`1& errorMessages)
   at Rock.Model.Workflow.ProcessActivity(RockContext rockContext, DateTime processStartTime, Object entity, List`1& errorMessages)
   at Rock.Model.Workflow.ProcessActivities(RockContext rockContext, Object entity, List`1& errorMessages)
   at Rock.Model.WorkflowService.Process(Workflow workflow, Object entity, List`1& errorMessages)
   at Rock.CheckIn.CheckInBlock.ProcessActivity(String activityName, List`1& errorMessages)
   at RockWeb.Plugins.cc_newspring.AttendedCheckin.FamilySelect.ProcessPeople(CheckInFamily selectedFamily) in c:\inetpub\wwwroot\Plugins\cc_newspring\AttendedCheckin\FamilySelect.ascx.cs:line 847
   at RockWeb.Plugins.cc_newspring.AttendedCheckin.FamilySelect.OnLoad(EventArgs e) in c:\inetpub\wwwroot\Plugins\cc_newspring\AttendedCheckin\FamilySelect.ascx.cs:line 149
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

**Comment by dcs619** [comment]
It sounds like you need to double-check the workflow configuration for that workflow action.  There is a Person and Group attribute that should be set but I've seen that attribute get unset during Rock updates.

**Comment by dcs619** [comment]
Closing, this will be fixed in the next Rock Shop update. 

If the Has Special Needs attributes are set correctly in the Attended Check-in workflow this will not throw exceptions.
