### ISSUE TITLE
Problems After Installation

### ISSUE THREAD

**Issue by craigmash** [KingdomFirst/rock-attended-checkin#55]
I just installed the plugin. My /checkin page now shows an error.

 NullReferenceException in App_Web_40odqq5m

Message
Object reference not set to an instance of an object.

Stack Trace

   at RockWeb.Blocks.CheckIn.Welcome.OnLoad(EventArgs e)
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

**Comment by craigmash** [comment]
Seems it is working now. Adding a location to the test kiosk seems to have fixed all errors. Weird.
