### ISSUE TITLE
B: New Family with Family Barcode

### ISSUE THREAD

**Issue by nateh777** [KingdomFirst/rock-attended-checkin#80]
# Expected Behavior

Add a family with a family barcode and it work

# Current Behavior

Add a family works fine until you try to include the family barcode, if you do it will not add the family correctly. It adds them to the database but doesn't close the modal and I am not sure if all the data was saved correctly for the family. 

# Failure Information (for bugs)

## Steps to Reproduce

Please provide detailed steps for reproducing the issue. 

1. Search for a phone number
2. If it doesn't exist or you find one click on "Add New Family"
3. Attempt to add a family with at least 1 adult and 1 child and a family barcode.
4. Modal doesn't disappear and the family will have been added but you cannot continue.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Rock Version: 9.4 and 10.1
* Attended Check-in Version: 1.8

## Failure Logs

Please include any relevant log snippets or files here.

`Object reference not set to an instance of an object.`

`
   at lambda_method(Closure , GroupMember )
   at System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements, Int32 count)
   at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at Rock.Model.GroupServiceExtensions.HeadOfHousehold(IQueryable`1 members) in C:\DEV\Rock\Rock\Model\GroupService.Partial.cs:line 1341
   at RockWeb.Plugins.cc_newspring.AttendedCheckin.FamilySelect.AddGroupMembers(Group familyGroup, List`1 newPeople, String barcode) in c:\DEV\Rock\RockWeb\Plugins\cc_newspring\AttendedCheckin\FamilySelect.ascx.cs:line 1376
   at RockWeb.Plugins.cc_newspring.AttendedCheckin.FamilySelect.lbSaveFamily_Click(Object sender, EventArgs e) in c:\DEV\Rock\RockWeb\Plugins\cc_newspring\AttendedCheckin\FamilySelect.ascx.cs:line 758
   at System.Web.UI.WebControls.LinkButton.OnClick(EventArgs e)
   at System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)`

**Comment by calvmann** [comment]
Hi @nateh777 - In general, have you gotten any of the barcodes to work using attended checkin? I have not been successful. Hoping we can connect if you are able to.
